//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samu_isafi
{
    using System;
    using System.Collections.Generic;
    
    public partial class emergysos
    {
        public int id { get; set; }
        public string createBy { get; set; }
        public string phoneNumber { get; set; }
        public string namePatient { get; set; }
        public string address { get; set; }
    }
}
