//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samu_isafi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class samuEntities1 : DbContext
    {
        public samuEntities1()
            : base("name=samuEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adresse> adresse { get; set; }
        public virtual DbSet<attendance> attendance { get; set; }
        public virtual DbSet<emergencycall> emergencycall { get; set; }
        public virtual DbSet<emergencycategory> emergencycategory { get; set; }
        public virtual DbSet<emergysos> emergysos { get; set; }
        public virtual DbSet<medicalrecord> medicalrecord { get; set; }
        public virtual DbSet<subcategory> subcategory { get; set; }
        public virtual DbSet<usermodel> usermodel { get; set; }
    }
}
