//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samu_isafi
{
    using System;
    using System.Collections.Generic;
    
    public partial class medicalrecord
    {
        public int id { get; set; }
        public string patientName { get; set; }
        public Nullable<System.DateTime> dateOfBirth { get; set; }
        public string bloodType { get; set; }
        public string iduser { get; set; }
    }
}
